#!/usr/bin/env python3
"""
Generates boards.txt for the Kratos / Hermes / Vyper Pico derivative
of earlephilhower/arduino-pico.

Design intent (per board spec):
  - Everything is FIXED (hardcoded property, no menu entry) EXCEPT CPU
    frequency, which is the only exposed Tools menu.
  - CPU frequency menu excludes anything above the chip's rated max
    (200MHz for RP2040, 150MHz for RP2350) -- i.e. no "(Overclock)"
    entries exist at all, so it is architecturally impossible to
    select an overclocked state from this menu.
  - Flash total is fixed at 2MB per board; the sketch/filesystem split
    is set per board below (see FS_SIZE in BOARDS).
  - Optimize is fixed at -O3.
  - Boot stage 2 is fixed. NOTE: RP2350 (Hermes) has no boot2 concept
    (build.boot2=none) -- its boot ROM parses flash directly. See
    README "Technical corrections" section.
"""

import os

RP2040_FREQS = [100, 50, 120, 125, 128, 133, 150, 176, 200]   # 100 first = default
RP2350_FREQS = [100, 50, 120, 125, 128, 133, 150]             # 100 first = default

ONE_MB = 1024 * 1024
KB128 = 128 * 1024

# (board_id, pretty_name, chip, boot2, usb_pid_base, fs_size_bytes)
BOARDS = [
    ("kratos",     "Kratos",     "rp2040", "boot2_w25q16jvxq_4_padded_checksum", "0xa001", KB128),
    ("hermes",     "Hermes",     "rp2350", None,                                  "0xa002", ONE_MB),
    ("vyperpico",  "Vyper Pico", "rp2040", "boot2_w25q16jvxq_4_padded_checksum", "0xa003", ONE_MB),
]

FLASH_TOTAL = 2 * 1024 * 1024
BASE_ADDR = 0x10000000
DELTA = {"rp2040": 4096, "rp2350": 8192}

VID = "0x2e8a"  # NOTE: this is Raspberry Pi Foundation's registered USB VID.
                # Reused here (as nearly every RP2040/2350 clone board does)
                # only because it is zero-cost. See README for the pid.codes
                # alternative if/when this ships as a commercial product.

out = []

def w(s=""):
    out.append(s)

w("# Kratos / Hermes / Vyper Pico -- derivative of earlephilhower/arduino-pico")
w("# Generated by tools/make_boards.py -- do not hand-edit, regenerate instead.")
w()
w("menu.freq=CPU Speed")
w()

for board_id, pretty, chip, boot2, pid, fs_size in BOARDS:
    variant = {"kratos": "kratos", "hermes": "hermes", "vyperpico": "vyper_pico"}[board_id]
    delta = DELTA[chip]
    eeprom_start = BASE_ADDR + FLASH_TOTAL - delta
    fs_start = eeprom_start - fs_size
    fs_end = eeprom_start
    flash_length = FLASH_TOTAL - delta - fs_size

    w("# -----------------------------------")
    w(f"# {pretty}")
    w("# -----------------------------------")
    w(f"{board_id}.name={pretty}")

    w(f"{board_id}.vid.0={VID}")
    w(f"{board_id}.pid.0={pid}")
    w(f"{board_id}.upload_port.0.vid={VID}")
    w(f"{board_id}.upload_port.0.pid={pid}")
    w(f"{board_id}.build.usbvid=-DUSBD_VID={VID}")
    w(f"{board_id}.build.usbpid=-DUSBD_PID={pid}")
    w(f"{board_id}.build.usbpwr=-DUSBD_MAX_POWER_MA=250")
    w(f"{board_id}.build.board={board_id.upper()}")

    if chip == "rp2040":
        w(f"{board_id}.build.mcu=cortex-m0plus")
        w(f"{board_id}.build.chip=rp2040")
        w(f"{board_id}.build.toolchain=arm-none-eabi")
        w(f"{board_id}.build.toolchainpkg=pqt-gcc")
        w(f"{board_id}.build.toolchainopts=-march=armv6-m -mcpu=cortex-m0plus -mthumb")
        w(f"{board_id}.build.uf2family=--family rp2040")
    else:
        w(f"{board_id}.build.mcu=cortex-m33")
        w(f"{board_id}.build.chip=rp2350")
        w(f"{board_id}.build.toolchain=arm-none-eabi")
        w(f"{board_id}.build.toolchainpkg=pqt-gcc")
        w(f"{board_id}.build.toolchainopts=-mcpu=cortex-m33 -mthumb -march=armv8-m.main+fp+dsp -mfloat-abi=softfp -mcmse")
        w(f"{board_id}.build.uf2family=--family rp2350-arm-s --abs-block")
        w(f"{board_id}.build.variantdefines=-D__PICO_RP2350A=1")
        w(f"{board_id}.build.psram_length=0x000000")

    w(f"{board_id}.build.variant={variant}")
    w(f"{board_id}.build.core=rp2040")
    w(f"{board_id}.build.ldscript=memmap_default.ld")

    if boot2:
        w(f"{board_id}.build.boot2={boot2}")
    else:
        w(f"{board_id}.build.boot2=none")

    w(f'{board_id}.build.usb_manufacturer="Kratos-Hermes-Vyper"')
    w(f'{board_id}.build.usb_product="{pretty}"')

    w(f"{board_id}.upload.maximum_size={flash_length}")
    w(f"{board_id}.upload.wait_for_upload_port=true")
    w(f"{board_id}.upload.erase_cmd=")
    w(f"{board_id}.serial.disableDTR=false")
    w(f"{board_id}.serial.disableRTS=false")
    w(f"{board_id}.build.f_cpu=100000000")
    w(f"{board_id}.build.led=")
    w(f"{board_id}.build.flash_total={FLASH_TOTAL}")
    w(f"{board_id}.build.flash_length={flash_length}")
    w(f"{board_id}.build.eeprom_start={eeprom_start}")
    w(f"{board_id}.build.fs_start={fs_start}")
    w(f"{board_id}.build.fs_end={fs_end}")

    w(f"{board_id}.build.flags.optimize=-O3")

    w(f"{board_id}.build.os=")
    w(f"{board_id}.build.flags.profile=")
    w(f"{board_id}.build.flags.rtti=-fno-rtti")
    w(f"{board_id}.build.flags.stackprotect=")
    w(f"{board_id}.build.flags.exceptions=-fno-exceptions")
    w(f"{board_id}.build.flags.libstdcpp=-lstdc++")
    w(f"{board_id}.build.debug_port=")
    w(f"{board_id}.build.debug_level=")
    w(f"{board_id}.build.usbstack_flags=")

    ram = "256k" if chip == "rp2040" else "512k"
    ram_bytes = 256 * 1024 if chip == "rp2040" else 512 * 1024
    w(f"{board_id}.build.ram_length={ram}")
    w(f"{board_id}.build.debugscript=picoprobe_cmsis_dap.tcl")
    w(f"{board_id}.upload.maximum_data_size={ram_bytes}")
    w(f"{board_id}.upload.tool=uf2conv")
    w(f"{board_id}.upload.tool.default=uf2conv")
    w(f"{board_id}.upload.tool.network=uf2conv-network")

    freqs = RP2040_FREQS if chip == "rp2040" else RP2350_FREQS
    seen = set()
    for f in freqs:
        if f in seen:
            continue
        seen.add(f)
        label = f"{f} MHz" + (" (Default)" if f == freqs[0] else "")
        w(f"{board_id}.menu.freq.{f}={label}")
        w(f"{board_id}.menu.freq.{f}.build.f_cpu={f}000000L")

    w()

repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
out_path = os.path.join(repo_root, "boards.txt")
with open(out_path, "w") as f:
    f.write("\n".join(out) + "\n")

print("wrote", len(out), "lines to", out_path)
